### ISSUE TITLE
Why `update` method both modifies data and returns it?

### ISSUE THREAD

**Issue by petar-donchev** [h2non/jsonpath-ng#10]
Wouldn't it be better if there are two methods in public API, one that modifies its argument and returns nothing, and one that does not modify it and returns a modified copy? Or just have one of these.

**Comment by michaelmior** [comment]
Having the method work like this means you can do some easier chaining in some cases. Both of the use cases you present are still possible. However, if you have a concrete proposal for improving the API, feel free to submit a pull request.
