### ISSUE TITLE
import: ModuleNotFoundError: No module named 'jsonpath_ng'

### ISSUE THREAD

**Issue by davidmpatterson** [h2non/jsonpath-ng#103]
After 'pip install jsonpath-ng' (or 'jsonpath_ng'), on starting Python, the above error is shown. Running on M1 machine, if that helps.

**Comment by 1wang-wood** [comment]
maybe your pip is belong to another python in your computer which not used by environment

**Comment by michaelmior** [comment]
@davidmpatterson I'm going to close this since there hasn't been any updates in over a year, but feel free to reopen if you're still having this issue.
