### ISSUE TITLE
Regex case insensitive

### ISSUE THREAD

**Issue by LongBeachHXC** [h2non/jsonpath-ng#105]
I have a scenario where I am trying to match on a user's email. The object will look like so:

```
{ 
    "result": [
        {
            "email": "Jon.Doe@google.com",
            "attr2": "attr2 value",
            "attr3": "attr3 value",
        }
    ]
}
```
And I'm trying to match with the following expression:

```
search_expression = parse('$.result[?(@.email =~ "jon.doe" )]')
```
It does not find the user object.

So, then I tried something like this and it still didn't work:

```
search_expression = parse('$.result[?(@.email =~ "/jon.doe/i" )]')
```

Is there a way to force the regex for case insensitive?

**Comment by cmcdougall** [comment]
Did you find a solution to this?

I can't even seem to get regex to work with a filter!

My JSON looks like:

```
{
    "results": {
        "output": "Scanning: OK\n"
    }
}
```

I expected the expression to work, but it returns no results:

`jsonpath_expr = parse('$.results.output[?(@=~"OK")]')`

Anyone able to help?

**Comment by dennis-sayed** [comment]
@LongBeachHXC i tested now this and work fine, but if we want to reset after standard behaviours there is a way?

**Comment by michaelmior** [comment]
@dennis-sayed That would indeed be the correct way to restore standard behavior (although you can leave off 0 as the final parameter since it's the default). Closing since this seems to resolved, but feel free to reopen if you're still having an issue.
