### ISSUE TITLE
getting JsonPathParserError('Parse error at %s:%s near token %s (%s)' error.

### ISSUE THREAD

**Issue by bjp-rocks** [h2non/jsonpath-ng#107]
Hi there,

how to parse a string containing spaces?

like if I run below command then it will raise above mentioned error JsonPathParserError('Parse error at %s:%s near token %s (%s)'  

**foo="'30'.result.data.power_supplies.Power Supplies[0]"
print(parse(foo))**

**Comment by 1wang-wood** [comment]
you can use quotes
![image](https://user-images.githubusercontent.com/52374858/205208744-5eecadfc-49e3-4c00-92be-ffa12bab3775.png)
