### ISSUE TITLE
Can I register custom functions?

### ISSUE THREAD

**Issue by norouzzadegan** [h2non/jsonpath-ng#111]
Hi, guys. 
I want create custom function in Jsonpath, For example I have a json alike below:

```python
[{
    "name':'/home/user/Desktop/test.txt',
    'executable': True,
    'binary': False,'type':'file'
}]
```

I Want get content a file in path "/home/user/Desktop/test.txt" based on its name in json. For example the query is 
``` $.[1].content()```
Can I create custom function in jasonpath-ng?

**Comment by 1wang-wood** [comment]
fork your own project
add a new class in jsonpath_ng.ext.string.py which named "Content" extends jsonpath_ng.jsonpath.ext.string.This
![image](https://user-images.githubusercontent.com/52374858/205207650-58f86b72-5e5e-4cf4-8730-b62aaffcd798.png)
implements find method in Content to return a file content
add an elif in jsonpath_ng.ext.parser.ExtentedJsonPathParser.p_jsonpath_named_operator method like
        ```
elif p[1].startswith("content("):
            p[0] = _string.Str(p[1])
```
then you can use jsonpath express like this $.[1].`content()` to read a file content

**Comment by michaelmior** [comment]
@norouzzadegan It seems like there's a solution here, so closing this but feel free to reopen if needed.
