### ISSUE TITLE
jsonpath_ng.exceptions.JsonPathParserError: Parse error at 1:37 near token 1 (NUMBER)

### ISSUE THREAD

**Issue by yangming9** [h2non/jsonpath-ng#123]
my patch key contain a number as a key(but it is real a str),Can we be compatible with this format

```json
my json example : {
    "modular": 213,
    "enable": true,
    "info":[
        {
          "feature_param_dict_list": [{
                "1" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                "2" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                "3" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                "4" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                "5" : [0],
                "6" : [0],
                "7" : [0, 0, 0, 0],
                "8" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                "9" : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                "10": [0, 0]
              }
          ]
        }]
}
```

my path example : `$.info[*].feature_param_dict_list[*].1[0]`

**Comment by michaelmior** [comment]
You should be able to quote the `1` and use the path `$.info[*].feature_param_dict_list[*].["1"][0]`.

**Comment by enkeefe-flexgen** [comment]
Fair, but other JSONPath programs consider something like `$.info[0].feature_param_dict_list[0].1` as a valid path to get the value of the "1" key in the `feature_param_dict_list`. I have ran into this issue as well for some of my data and it would be wonderful if paths like the one above were supported.

**Comment by michaelmior** [comment]
This just required a change to the parser that doesn't appear to break any existing code, so this should be fixed in the next release.
