### ISSUE TITLE
`decorator` dependency is unused

### ISSUE THREAD

**Issue by reweeden** [h2non/jsonpath-ng#125]
I noticed that the `decorator` dependency appears to be unused when auditing the dependency tree of one of my projects to trim out unused dependencies. I am not familiar with this project's code, but running a `grep` over the code didn't come up with any hits for `decorator`, so I think it's safe to delete from the requirements file.

Thanks!

**Comment by michaelmior** [comment]
The `decorator` dependency has been removed (although the latest version is not yet released on PyPI).
