### ISSUE TITLE
&& not supported in JSONPath

### ISSUE THREAD

**Issue by athario** [h2non/jsonpath-ng#129]
This is a valid JSONPath query:

`$.dataset[?(@.property_type_1 == 1 && @.property_type_2 == 1)]`

however the following response is received:

`jsonpath_ng.exceptions.JsonPathParserError: Parse error at 1:48 near token & (&)`

(1:48 is not the correct position due to obfuscation)

It would be great to be able to do this as it enables dual filtering.

**Comment by michaelmior** [comment]
You should be able to use a single ampersand for this.

**Comment by michaelmior** [comment]
Closing as this should be resolvable with a slight change in the expression. Please reopen if this doesn't solve your issue.
