### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by return42** [h2non/jsonpath-ng#131]
This is a very useful project :+1:, I am thinking of including jsonpath-ng in my project. But I'm not quite sure what the maintenance status is; in the error messages and PRs I see unprocessed entries and the last release is from 2021 https://pypi.org/project/jsonpath-ng/#history ... Apart from https://github.com/h2non/jsonpath-ng/pull/128 there doesn't seem to have been any substantial changes since then ... hence my question to the project team if there are any further plans for this project.

Thanks in advance :+1:

**Comment by michaelmior** [comment]
The original owner is not currently active in the project. As a user, I've been given access to the repo and I've been trying to make some improvements where I can, but I can't make any specific guarantees.
