### ISSUE TITLE
Please release 1.6.1 with the following fixes

### ISSUE THREAD

**Issue by arcivanov** [h2non/jsonpath-ng#157]
https://github.com/h2non/jsonpath-ng/commit/be2d59370500c0bcf96082dbf35c0f6ea733ba9d

**Comment by arcivanov** [comment]
https://github.com/h2non/jsonpath-ng/commit/b503208c5bd941da501dd55ebb9fd433b755edfd

**Comment by michaelmior** [comment]
v1.6.1 was just released :)

**Comment by arcivanov** [comment]
Thank you!
