### ISSUE TITLE
Add Original Path to JSONPath Expression Object

### ISSUE THREAD

**Issue by bpna** [h2non/jsonpath-ng#158]
Hi,

Can we add an attribute for the original path supplied to create the JSONPath expression?

So with:
```
from jsonpath_ng import parse

jsonpath_expr = parse('data.results')
```

We have something like
```
jsonpath_expr.path
```
that returns:
```
'data.results'
```

**Comment by bpna** [comment]
Oh my bad this is actually maybe just the `fields` attribute...

So
```
jsonpath_expr.fields[0] == 'data.results'
```

**Comment by bpna** [comment]
It looks like `fields` is only available for a `Fields` object

For a `Child` object, there is no `fields` attribute

So you get an `AttributeError` with following:
```
>>> resulst_expr = jsonpath_ng.parse('nested.path')
>>> results_expr.fields[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Child' object has no attribute 'fields'
```

**Comment by michaelmior** [comment]
It's not guaranteed to convert back to exactly the original string, but you can always use `str` on the path object.

```python
>>> results_expr = jsonpath_ng.parse('nested.path')
>>> str(results_expr)
'nested.path'
```

As an example where you might not get back exactly the original path, consider `"nested".path` which has unnecessary quoting.

```python
>>> results_expr = jsonpath_ng.parse('"nested".path')
>>> str(results_expr)
'nested.path'
```

Note that `"nested".path` and `nested.path` are equivalent.

**Comment by bpna** [comment]
This is what I needed, thank you!
