### ISSUE TITLE
Cannot find items in data structure

### ISSUE THREAD

**Issue by shahargli** [h2non/jsonpath-ng#174]
Hello,

I am trying to use jsonpath_ng.ext to find items in a json data structure.
Following is the program, where I expected to find one item (panels.datasource.type=='type1'), but 
 find() always returns empty list
```python
from jsonpath_ng.ext import parse

data = {
    'panels': [
        {
            'datasource': {'type': 'type1'},
        },
        {
            'datasource': {'type': 'type2'},
        }
    ]
}
jsonpath_expr = parse('panels.datasource[?(@.type=="type1")]')
found = jsonpath_expr.find(data)
print(found)
```

**Comment by michaelmior** [comment]
Your syntax is not quite right. The filter syntax, that is `[?…]` operates on arrays. If you try instead `panels[?datasource.type = "type1"]`, you'll get `{"datasource": {"type": "type1"}` in your results.

**Comment by michaelmior** [comment]
I'm going to close this, but feel free to reopen if you still have questions.
