### ISSUE TITLE
How to tell if a JsonPath is contained within a JsonPath filter?

### ISSUE THREAD

**Issue by accupham** [h2non/jsonpath-ng#178]
I'm looking for something that can conceptually compare JsonPaths themselves, and not instances of JSON. For example:

```python
j1 = parse("my.json.path.*.filter")
j2 = parse("my.json.path.anything.filter")

assert j2.issubset(j1)

j3 =  parse("users[*].name.*")
j4 = parse("users[42].name.id")

assert j4.issubset(j3)
```

**Comment by michaelmior** [comment]
@accupham This isn't a functionality that this package provides. I suspect you'd run into a lot of edge cases that would be challenging to handle. I'd be open to looking at a PR if you were to try implementing such functionality, but aside from that, I don't think there's an easy solution.
