### ISSUE TITLE
Missing v1.4.3 tag

### ISSUE THREAD

**Issue by Cynerd** [h2non/jsonpath-ng#18]
The newest version seems to be 1.4.3 on pypi but there is no tag for it. This version seems to be uploaded some commit after this one: 8e4693b7327f2d528d54198d773d4942ed240f1a

Please tag this version in git so it is clear what version of sources 1.4.3 really specially for those that are not using pip to install it (I am packaging it).

**Comment by michaelmior** [comment]
@Cynerd Unfortunately this release was so old now that retroactively tagging is a bit challenging. If this is still important, feel free to reopen and we could perhaps find a way to compare the PyPI versions against the git history.
