### ISSUE TITLE
Latest version release

### ISSUE THREAD

**Issue by nitoygo** [h2non/jsonpath-ng#180]
First of all, great project!

When would the latest version in master have a release?  
I kinda need the latest commits (regarding the split regex update) without having to subtree this repo into my app.

Cheers.

**Comment by michaelmior** [comment]
@nitoygo It's not a perfect solution, but note that pip does allow you to [install dependencies that reference a specific commit in a git repository](https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip) instead of using PyPI.

**Comment by michaelmior** [comment]
Version 1.7.0 has now been released.

**Comment by denisfrm** [comment]
Hey @michaelmior , when will the new release be launched?
