### ISSUE TITLE
Missing wheel for 1.7.0 release

### ISSUE THREAD

**Issue by edgarrmondragon** [h2non/jsonpath-ng#184]
The [1.7.0 release in PyPI](https://pypi.org/project/jsonpath-ng/#files) is missing the pure-Python wheel and only the sdist is present.

Previous releases did include a wheel, but the release process doesn't seem to be documented or automated, so I can't tell what went wrong.

Thanks!

**Comment by fervand1** [comment]
Any update on this? It is causing issues in the ci due to this version of dependency. Or can this release be yanked till the wheel is fixed? Thanks

**Comment by pvieito** [comment]
+1, same issue here!

**Comment by michaelmior** [comment]
Sorry for the delay. The wheel has been uploaded. It's on my todo list to fully automate the release process especially now that PyPI supports attestations.
