### ISSUE TITLE
Importing test library 'REST' failed: ModuleNotFoundError: No module named 'jsonpath_ng.bin'; 'jsonpath_ng' is not a package

### ISSUE THREAD

**Issue by mayuresh1612** [h2non/jsonpath-ng#36]
**For jsonpath-ng 1.5.0 released today got some issue**

Importing test library 'REST' failed: ModuleNotFoundError: No module named 'jsonpath_ng.bin'; 'jsonpath_ng' is not a package

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/REST/__init__.py", line 37, in <module>
    from .keywords import Keywords
  File "/usr/local/lib/python3.8/site-packages/REST/keywords.py", line 34, in <module>
    from jsonpath_ng.ext import parse as parse_jsonpath
  File "/usr/local/bin/jsonpath_ng.py", line 5, in <module>
    from jsonpath_ng.bin.jsonpath import entry_point

**_Please Note: Working fine with jsonpath-ng==1.4.3_**

**Comment by gaborbernat** [comment]
@h2non this is related to https://github.com/h2non/jsonpath-ng/pull/25; that name choice for the executable is a really bad idea.

Python puts the current working directory always on the path, as first entry, see https://docs.python.org/3/tutorial/modules.html#the-module-search-path. So if someone executes ``import jsonpath_ng`` from the binary folder Python will import the generated console script as ``jsonpath_ng``, which in turn, of course, does not have the needed sub-packages.

cc @rahendatri for awareness

**Comment by h2non** [comment]
This should be fixed in `v1.5.1`, now available on PyPI. To upgrade, please run:
`pip install --upgrade jsonpath-ng`

**Comment by gaborbernat** [comment]
Thanks 👍
