### ISSUE TITLE
Problems with documentation on extensions in README

### ISSUE THREAD

**Issue by baynes** [h2non/jsonpath-ng#56]
1: After the "Extensions" heading https://github.com/h2non/jsonpath-ng#extensions there should be a reminder that you have to use jsonpath_ng.**ext**.parse, not jsonpath_ng.parse to use these.

2 The following examples are wrong:
```
$.objects[?some_field = "foobar")]
$.objects[?some_field =~ "foobar")]
$.objects[?some_field > 5 & other < 2)]
```
They are missing a "(" and possibly also "@." after the "?".

**Comment by trebor74hr** [comment]
Maybe someone will find useful - I have provided working example that uses filter functions from extensions on https://stackoverflow.com/questions/12343282/python-jsonpath-filter-expression/64970342#64970342

**Comment by michaelmior** [comment]
I added a note about importing from `jsonpath_ng.ext` in the README.
