### ISSUE TITLE
I'm having an error trying to create a JSONPath - Exception: Parse error at 1: 4 near token? (?)

### ISSUE THREAD

**Issue by kespineira** [h2non/jsonpath-ng#75]
Hi!

I am trying to create a filter on the following JSON but for some reason I am getting the error all the time:

> Exception: Parse error at 1: 4 near token? (?)

This is my code: 

```
from jsonpath_ng import jsonpath
from jsonpath_ng.ext import parse

r = requests.get(url, headers=json.loads(headers))
j = r.text
j_exp = parse("$..[?(@name == 'CCAA')].idAssetType")
id = j_exp.find(j)
print(id)
```

Confirm that the value of **j** is:

> [{"idAssetType":6,"name":"CCAA","enterprise":{"id":1,"name":"APV"}}]

**Comment by nivesnine** [comment]
remove the ".." after the "$"

`j_exp = parse("$[?(@.name == 'CCAA')].idAssetType")`

and if you only want the idAssetType:

`print(id[0].value)`

**Comment by michaelmior** [comment]
This seems to be resolved, so closing. If there are still any problems, feel free to reopen.

**Comment by lalitmahato** [comment]
Hello everyone,
I faced the same issue while getting the data. My expression looks like ```$..[?(@.name=='is_literate')]```  it throws error. Also, I tried ```$[?(@.name=='is_literate')]``` this time, this does not throw any error, but I did not get the expected value. Which is given as follows. I tried it at https://jsonpath.com/,  it works fine with ```$..[?(@.name=='is_literate')]```  expression.
```
[
  {
    "control": {
      "appearance": "quick"
    },
    "children": [
      {
        "name": "is_literate_1",
        "label": "साक्षर"
      },
      {
        "name": "is_literate_0",
        "label": "निरक्षर"
      }
    ],
    "name": "is_literate",
    "label": "${full_name}: साक्षर कि निरक्षर ?",
    "bind": {
      "required": "true"
    },
    "type": "select one"
  }
]
```

I am attaching the JSON file for reference. I would appreciate it if someone could resolve this issue. Thank You.
[Json File](https://github.com/user-attachments/files/21955956/form_label_output.json)
