### ISSUE TITLE
Removed "forked" Github status

### ISSUE THREAD

**Issue by pauldraper** [h2non/jsonpath-ng#86]
Github forked repositories are 2nd class citizens. E.g. code search is completely non-functional.

I suggest removing the forked status.

https://stackoverflow.com/a/16052845/1212596

**Comment by michaelmior** [comment]
@pauldraper Perhaps this is just outdated since this issue is old, but you clarify what you mean by code search being non-functional? I don't seem to have any problems searching the repository.

**Comment by pauldraper** [comment]
@michaelmior you are correct; I currently have no issue searching.

**Comment by michaelmior** [comment]
I'm going to close this for now although it can certainly be revisited if there are any issues in the future.
