### ISSUE TITLE
Unexpected character '#'

### ISSUE THREAD

**Issue by Provinm** [h2non/jsonpath-ng#9]
when i run code belows
```python
from jsonpath_ng import jsonpath, parse
dct = {'A#B': [1,2,3]}
pt = parse('A#B')
print pt.find(dct)
```
it gives me `JsonPathLexerError: Error on line 1, col 1: Unexpected character: #  `

so, is there any method or extra setting  i can solve this problem?

in addition, i want to know which characters will meet the same problem?

thanks.

**Comment by dlacher1** [comment]
https://github.com/kennknowles/python-jsonpath-rw/commit/2ceae1039208973e9fe1588011c902e231144efe check out this PR. you could try editing these regular expression to allow for # in the name. this was reverted but im not sure why

**Comment by michaelmior** [comment]
@Provinm If you quote the path, i.e. `'"A#B"`, then it will work as expected.
