### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by and-semakin** [h2non/jsonpath-ng#92]
It's already the end of 2021. Python 2 has been officially unsupported for 2 years already. It seems like it may be a good moment to drop Python 2 support.

According to the [PyPI stats](https://www.pypistats.org/packages/jsonpath-ng), there are only 1-4% of users still on Python 2, and the number continues to decrease.

![Screenshot from 2021-10-26 10-53-00](https://user-images.githubusercontent.com/9129071/138816981-6a114839-67f0-415f-8102-04d875acfb62.png)

I suggest the following plan:
1. make a new release with `python_requires` directive set to Python 3 only (see [post in Pallets blog about it](https://palletsprojects.com/blog/ending-python2-support/)).
2. upgrade the code to use new syntax (actually break Python 2 compatibility), for exaple, using [`pyupgrade`](https://github.com/asottile/pyupgrade).

What do you think?

**Comment by michaelmior** [comment]
There is no new release on PyPI yet, but Python 2 support has been dropped.
